### ISSUE TITLE
Using version 1.1.3 and have Rsocket Error

### ISSUE THREAD

**Issue by keyhan** [linux-china/xtermjs-spring-boot-starter#4]
I start the version 1.1.3 (Tested with version 1.1.1 with the same result) of application and I added the properties as you mentioned here, it goes up but then I see the error message when I type help in the console:

```
  Xterm for null
  
  $help
  Failed to connect RSocket backend(ws://localhost:8080/rsocket), please check your service! 
```

**Comment by keyhan** [comment]
The application log itself does not show any warnings or errors.

**Comment by michalbalicki** [comment]
Had the same issue; resolved by changing dependency from spring-boot-starter-web into spring-boot-starter-webflux and explicitly adding spring-boot-starter-rsocket.

**Comment by linux-china** [comment]
@keyhan  @michalbalicki  Could you update to 1.2.1?  I just released the last version.
